version: "3.8"
services:
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf
    container_name: mobsf
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build: .
    container_name: saf-web
    ports:
      - "5000:5000"
    environment:
      - MOBSF_URL=http://mobsf:8000
      - MOBSF_API_KEY=${MOBSF_API_KEY}
      - FLASK_SECRET=some-secret
    depends_on:
      - mobsf
    restart: unless-stopped
